### ISSUE TITLE
FEATURE: Set Timeout

### ISSUE THREAD

**Issue by thatsjet** [parnic/node-screenlogic#71]
Hey, really love the work here.

I'm writing an Alexa skill that controls various features and find that some are slower than others to respond with state confirmation. Would be super rad if we could set a config on the constructor to set a timeout vs. the default 2300ms.

**Comment by parnic** [comment]
Have you seen how the example script handles a unit coming in immediately instead of awaiting the entire timeout? I agree it would be nice to be able to adjust the timeout, but perhaps the other mode would be more future-proof for you where it would work regardless of how slow or fast the unit responds.

**Comment by thatsjet** [comment]
No, but I'll check that out. Thanks!

**Comment by thatsjet** [comment]
Actually, my bad. I was calling `circuits.setCircuitStateAsync()` without await. Added await and it finishes fine.

**Comment by parnic** [comment]
Great!
